apiVersion: v2
name: garage-webui
description: A Helm chart for the Garage Web UI (genebit/s3-garagehq-webui), an admin web UI for the Garage S3 object store
type: application
version: 1.0.0-pre.2
appVersion: "1.1.0"
kubeVersion: ">=1.19.0-0"
keywords:
  - garage
  - s3
  - object-storage
  - webui
home: https://github.com/genebit/s3-garagehq-webui
sources:
  - https://github.com/genebit/s3-garagehq-webui
  - https://git.aquila-consortium.org/guilhem_lavaux/helm-garage-webui
