{{- $data := include "garage-webui.secretData" . | trim }}
{{- if $data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garage-webui.secretName" . }}
  labels:
    {{- include "garage-webui.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $data | nindent 2 }}
{{- end }}
